#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caffeinate-me"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
