# fly.toml app configuration file generated for caffeinate-me on 2023-06-17T17:19:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caffeinate-me"
primary_region = "ewr"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
